//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despesa
    {
        public int Id_Viatura { get; set; }
        public int Id_Fornecedor { get; set; }
        public Nullable<System.DateTime> DataDespesa { get; set; }
        public string NºFatura { get; set; }
        public string PedidoCompra { get; set; }
        public Nullable<int> Preço { get; set; }
        public string NomeDespesa { get; set; }
        public int Id_Despesa { get; set; }
    
        public virtual Fornecedores Fornecedores { get; set; }
        public virtual Viatura Viatura { get; set; }
    }
}
