//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kilometros
    {
        public int Id_Viatura { get; set; }
        public Nullable<System.DateTime> DataRegisto { get; set; }
        public Nullable<int> QuantidadeKm { get; set; }
        public int Id_Kilometros { get; set; }
    
        public virtual Viatura Viatura { get; set; }
    }
}
